### ISSUE TITLE
Create Env Error

### ISSUE THREAD

**Issue by hnglp** [maincold2/Compact-3DGS#12]
when i try to create env. i get this error anyone know why is that

```
Installing pip dependencies: - Ran pip subprocess with arguments:
['C:\\Users\\alpak\\anaconda3\\envs\\halp\\envs\\c3dgs\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\alpak\\OneDrive\\Desktop\\alp\\take_home_exam\\SLAMPy-Monocular-SLAM-implementation-in-Python\\Compact-3DGS\\condaenv.f9b2y9ry.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch (from -r C:\Users\alpak\OneDrive\Desktop\alp\take_home_exam\SLAMPy-Monocular-SLAM-implementation-in-Python\Compact-3DGS\condaenv.f9b2y9ry.requirements.txt (line 3))
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\alpak\appdata\local\temp\pip-req-build-tzed9wl8
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 235d1fde956dc04966940f9d1bec66aa3bdb705a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\alpak\AppData\Local\Temp\pip-req-build-tzed9wl8'
  Running command git submodule update --init --recursive -q
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      C:\Users\alpak\AppData\Local\Temp\pip-req-build-tzed9wl8\bindings/torch\setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\alpak\AppData\Local\Temp\pip-req-build-tzed9wl8\bindings/torch\setup.py", line 51, in <module>
          raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
      OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1'
      Building PyTorch extension for tiny-cuda-nn version 1.7
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

**Comment by maincold2** [comment]
Are you trying on Windows?
It seems to have some trouble installing tiny-cudn-nn, so please refer to its requirements (https://github.com/NVlabs/tiny-cuda-nn).

Thanks!

**Comment by EvenJie-XR** [comment]
I get this error too, Have you found a good solution?
```
Installing pip dependencies: \ Ran pip subprocess with arguments:
['C:\\Users\\zwj\\.conda\\envs\\c3dgs\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'E:\\Code\\Python\\SZU\\Compact-3DGS\\condaenv.w3k2v8oo.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch (from -r E:\Code\Python\SZU\Compact-3DGS\condaenv.w3k2v8oo.requirements.txt (line 3))
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\zwj\appdata\local\temp\pip-req-build-x7u26lvj
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 235d1fde956dc04966940f9d1bec66aa3bdb705a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\zwj\AppData\Local\Temp\pip-req-build-x7u26lvj'
  Running command git submodule update --init --recursive -q
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      C:\Users\zwj\AppData\Local\Temp\pip-req-build-x7u26lvj\bindings/torch\setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\zwj\AppData\Local\Temp\pip-req-build-x7u26lvj\bindings/torch\setup.py", line 72, in <module>
          raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
      RuntimeError: Could not locate a supported Microsoft Visual C++ installation
      Building PyTorch extension for tiny-cuda-nn version 1.7
      Obtained compute capability 86 from PyTorch
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

**Comment by hnglp** [comment]
I use VS Code as my code editor, but it's mentioned that it has been tested and works flawlessly in Visual Studio 2022 under the tinny-cuda repository. Additionally, when installing Cuda Toolkit 11.6, it says that it couldn't find a correctly matched version of Visual Studio. Do you think the problem might stem from this? Could it be that VS Code as a code editor is insufficient?

@maincold2

**Comment by maincold2** [comment]
Because I'm not a user of either Windows or VSCode, I can not be sure, but I think VSCode is not the matter.
Have you tried the following command before creating env? (command line for Windows users in 3DGS):
SET DISTUTILS_USE_SDK=1

If you can create an env of 3DGS, based on which you can set by installing tiny-cuda-nn manually I think.

**Comment by hnglp** [comment]
Yes i tried that command before creating env but I think the problem stems from my GPU; even though PyTorch is installed correctly, it seems it is not installed with CUDA support, and my current GPU, I believe, does not support this CUDA version, which causes issues with the tiny-CUDA-NN package. However, I still want to ask one last thing: Do you think manually installing the packages expected to be installed via pip one by one is an appropriate method?

Thanks again.

**Comment by maincold2** [comment]
It would be nice to check that only installing tinycudann is the matter.
Once you succeed in setting 3DGS's environment, you may install tinycudann (building manually if needed) and a few other packages (e.g., dahuffman, pytorch VQ).
