### ISSUE TITLE
RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by weijielyu** [maincold2/Compact-3DGS#2]
Hi, thanks for this great work. I ran into a bug when working with the Blender dataset. Here's my command
```
CUDA_LAUNCH_BLOCKING=1 python train.py -s /nerf_synthetic/chair -m output/blender/chair --eval
```
When training to 7400 iterations
```
Training progress:  25%|█████████████████▊                                                      | 7400/30000 [03:13<04:37, 81.46it/s, Loss=0.1525732]Traceback (most recent call last):
  File "train.py", line 244, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 84, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background, itr=iteration, rvq_iter=False)
  File "/home/tmp/Compact-3DGS/gaussian_renderer/__init__.py", line 97, in render
    cov3D_precomp = None)
  File "/home/tmp/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tmp/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 219, in forward
    raster_settings, 
  File "/home/tmp/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 41, in rasterize_gaussians
    raster_settings,
  File "/home/tmp/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: CUDA error: invalid configuration argument
Training progress:  25%|█████████████████▊                                                      | 7400/30000 [03:13<09:52, 38.16it/s, Loss=0.1525732]
```
I wonder do you have any idea about this error?

Thank you!

**Comment by maincold2** [comment]
Thank you for your interest in our work!

For synthetic scenes, we used some different parameters, as mentioned in section 4.1 of the paper.
Please refer to the updated readme.
